### ISSUE TITLE
how do i run it?

### ISSUE THREAD

**Issue by pyxiaoai** [laurentpayot/minidenticons#6]
how do i run it?

**Comment by laurentpayot** [comment]
- If you want to run it inside a web browser, then read [this](https://github.com/laurentpayot/minidenticons#basic-usage-with-the-included-custom-element).

- If you want to run it on a local development machine, first [install Node.js](https://nodejs.org/en/download/current), and then read [this](https://github.com/laurentpayot/minidenticons#advanced-usage-with-the-minidenticon-function).

If you are new to web development, the [source code](https://github.com/laurentpayot/minidenticons/blob/main/index.html) of the [demo](https://laurentpayot.github.io/minidenticons/) is a good "Vanilla JavaScript" usage example.

Does this answer your question?

**Comment by laurentpayot** [comment]
Closing the issue for lack of feedback.
