### ISSUE TITLE
I can't run in nodejs

### ISSUE THREAD

**Issue by quangbeuu** [laurentpayot/minidenticons#7]
Now i use node v18 and typescript, but when I install by `yarn add minidenticons` and when I run `yarn start` I got an errors like this. Please help me fix this :((( 
<img width="1010" alt="error" src="https://github.com/laurentpayot/minidenticons/assets/91740402/9fde34a1-590f-4a59-830e-09217fec84b7">

**Comment by quangbeuu** [comment]
I use `import` instead `require` but still error

**Comment by quangbeuu** [comment]
I had fixed this bug. I use dynamic import() like this
![Screenshot 2024-01-05 at 00 19 23](https://github.com/laurentpayot/minidenticons/assets/91740402/d11bf691-0815-437b-b978-38e30eb67c9a)

**Comment by laurentpayot** [comment]
Weird. I would need to see your code to understand why it wasn’t working. I’m glad you could fix it, even if dynamic import is not the best way for such a tiny library.
